version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/v4-frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      frontend-dependencies:
        patterns:
          - "*"
