create table if not exists public.publication_watchdog_events (
  id bigint generated by default as identity primary key,
  article_id uuid not null references public.articles(id) on delete cascade,
  issue_type text not null check (issue_type in ('blocked','publish_failed','auto_released')),
  reason text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists publication_watchdog_events_article_created_idx
  on public.publication_watchdog_events(article_id, created_at desc);

create unique index if not exists publication_watchdog_events_open_issue_uq
  on public.publication_watchdog_events(article_id, issue_type)
  where resolved_at is null and issue_type in ('blocked','publish_failed');

alter table public.publication_watchdog_events enable row level security;
revoke all on table public.publication_watchdog_events from public, anon, authenticated;
grant select, insert, update on table public.publication_watchdog_events to service_role;
grant usage, select on sequence public.publication_watchdog_events_id_seq to service_role;

create or replace function public.article_media_publication_error(
  p_media_id uuid,
  p_hero_url text
)
returns text
language plpgsql
stable
set search_path = public
as $$
declare
  asset public.media_assets%rowtype;
begin
  if p_media_id is null then
    return 'missing_hero_media_id';
  end if;

  select * into asset
  from public.media_assets
  where id = p_media_id;

  if not found then return 'hero_media_not_found'; end if;
  if asset.status <> 'ready' then return 'hero_media_not_ready'; end if;
  if not asset.commercial_use_allowed then return 'commercial_use_not_allowed'; end if;
  if not asset.local_storage_allowed then return 'local_storage_not_allowed'; end if;
  if asset.delivery_url is null or btrim(asset.delivery_url) = '' then return 'missing_delivery_url'; end if;
  if p_hero_url is distinct from asset.delivery_url then return 'hero_url_mismatch'; end if;
  if asset.attribution_required and (asset.credit_text is null or btrim(asset.credit_text) = '') then
    return 'missing_required_attribution';
  end if;

  return null;
end;
$$;

create or replace function public.validate_article_media()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  is_new_publication boolean := false;
  media_error text;
begin
  if new.status <> 'published'::public.article_status then
    return new;
  end if;

  is_new_publication := tg_op = 'INSERT'
    or old.status is distinct from 'published'::public.article_status;

  if new.hero_media_id is null then
    if is_new_publication
      or (tg_op = 'UPDATE' and old.hero_media_id is not null) then
      raise exception 'published articles require an archived hero_media_id';
    end if;
    return new;
  end if;

  media_error := public.article_media_publication_error(new.hero_media_id, new.hero_url);

  case media_error
    when null then null;
    when 'hero_media_not_found' then raise exception 'hero_media_id does not reference an existing media asset';
    when 'hero_media_not_ready' then raise exception 'hero media asset must be ready before publication';
    when 'commercial_use_not_allowed' then raise exception 'hero media asset lacks required commercial/archive rights';
    when 'local_storage_not_allowed' then raise exception 'hero media asset lacks required commercial/archive rights';
    when 'missing_delivery_url' then raise exception 'hero media asset has no delivery URL';
    when 'hero_url_mismatch' then raise exception 'published hero_url must match the archived media asset delivery URL';
    when 'missing_required_attribution' then raise exception 'hero media asset requires attribution but has no credit text';
    else raise exception 'hero media validation failed: %', media_error;
  end case;

  return new;
end;
$$;

create or replace function public.publish_article_safely(p_article_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  article public.articles%rowtype;
  media_error text;
  v_now timestamptz := clock_timestamp();
begin
  select * into article
  from public.articles
  where id = p_article_id
  for update;

  if not found then
    raise exception 'article not found: %', p_article_id;
  end if;

  if article.status = 'published'::public.article_status then
    return article.id;
  end if;

  media_error := public.article_media_publication_error(article.hero_media_id, article.hero_url);
  if media_error is not null then
    insert into public.publication_watchdog_events(article_id, issue_type, reason, details)
    values (article.id, 'blocked', media_error,
      jsonb_build_object('source','publish_article_safely','status',article.status,'publish_at',article.publish_at))
    on conflict (article_id, issue_type) where resolved_at is null and issue_type in ('blocked','publish_failed')
    do update set reason=excluded.reason, details=excluded.details, created_at=now();

    raise exception 'article is not publication-ready: %', media_error;
  end if;

  update public.articles
     set status = 'published'::public.article_status,
         publish_at = coalesce(article.publish_at, v_now),
         published_at = coalesce(article.published_at, article.publish_at, v_now),
         editorial_metadata = coalesce(article.editorial_metadata, '{}'::jsonb)
           || jsonb_build_object('publication_requested_at',v_now,'publication_path','safe_publish')
   where id = article.id;

  update public.publication_watchdog_events
     set resolved_at = coalesce(resolved_at, v_now)
   where article_id = article.id
     and resolved_at is null
     and issue_type in ('blocked','publish_failed');

  return article.id;
end;
$$;

revoke all on function public.publish_article_safely(uuid) from public, anon, authenticated;
grant execute on function public.publish_article_safely(uuid) to service_role;

create or replace function public.run_publication_watchdog()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := clock_timestamp();
  article record;
  media_error text;
begin
  for article in
    select a.id, a.status, a.publish_at, a.hero_media_id, a.hero_url, a.editorial_metadata
    from public.articles a
    where a.status = 'scheduled'::public.article_status
      and a.publish_at is not null
      and a.publish_at <= v_now - interval '3 minutes'
    order by a.publish_at
    for update skip locked
  loop
    media_error := public.article_media_publication_error(article.hero_media_id, article.hero_url);

    if media_error is not null then
      insert into public.publication_watchdog_events(article_id, issue_type, reason, details)
      values (article.id, 'blocked', media_error,
        jsonb_build_object('source','publication_watchdog','publish_at',article.publish_at,'checked_at',v_now))
      on conflict (article_id, issue_type) where resolved_at is null and issue_type in ('blocked','publish_failed')
      do update set reason=excluded.reason, details=excluded.details, created_at=now();

      update public.articles
         set editorial_metadata = coalesce(editorial_metadata, '{}'::jsonb)
           || jsonb_build_object(
                'publication_watchdog',
                jsonb_build_object('state','blocked','reason',media_error,'checked_at',v_now)
              )
       where id = article.id;
      continue;
    end if;

    begin
      update public.articles
         set status = 'published'::public.article_status,
             editorial_metadata = coalesce(editorial_metadata, '{}'::jsonb)
               || jsonb_build_object(
                    'publication_watchdog',
                    jsonb_build_object('state','auto_released','checked_at',v_now,'original_publish_at',article.publish_at)
                  )
       where id = article.id;

      insert into public.publication_watchdog_events(article_id, issue_type, reason, details, resolved_at)
      values (article.id, 'auto_released', null,
        jsonb_build_object('original_publish_at',article.publish_at,'released_at',v_now), v_now);

      update public.publication_watchdog_events
         set resolved_at = coalesce(resolved_at, v_now)
       where article_id = article.id
         and resolved_at is null
         and issue_type in ('blocked','publish_failed');
    exception when others then
      insert into public.publication_watchdog_events(article_id, issue_type, reason, details)
      values (article.id, 'publish_failed', sqlstate,
        jsonb_build_object('source','publication_watchdog','message',sqlerrm,'publish_at',article.publish_at,'checked_at',v_now))
      on conflict (article_id, issue_type) where resolved_at is null and issue_type in ('blocked','publish_failed')
      do update set reason=excluded.reason, details=excluded.details, created_at=now();
    end;
  end loop;

  update public.publication_watchdog_events e
     set resolved_at = coalesce(e.resolved_at, v_now)
   where e.resolved_at is null
     and e.issue_type in ('blocked','publish_failed')
     and exists (
       select 1 from public.articles a
       where a.id = e.article_id
         and a.status = 'published'::public.article_status
     );
end;
$$;

revoke all on function public.run_publication_watchdog() from public, anon, authenticated;
grant execute on function public.run_publication_watchdog() to service_role;

select cron.unschedule(jobid)
from cron.job
where jobname = 'publication-watchdog';

select cron.schedule(
  'publication-watchdog',
  '* * * * *',
  'select public.run_publication_watchdog();'
);
